### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Lunaxod/Ringostat-GTM-Server-side-client#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The "homepage", "documentation" url mentioned in the metadata file shows blank page without any info. Please provide valid url's.
![Screenshot 2021-04-20 12 25 17 PM](https://user-images.githubusercontent.com/53495700/115452732-a8f91680-a1d3-11eb-8372-dc919b90e785.png)
2) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on projectHash when generating the url
let SCRIPT_SRC = '/v4/' + projectHash.substring(0, 2) + '/' + projectHash + '.js';

**Comment by Lunaxod** [comment]
Fixed
